#!/bin/bash
# Usage: handles server
# Summary: Start the project locally

set -e

cd "$(git rev-parse --show-toplevel 2>/dev/null)"

handles-update

if [ -f "Procfile" ] || [ -f "Procfile.local" ]; then
  test -f "Procfile.local" && PROCFILE="Procfile.local"

  if ! command -v forego >/dev/null 2>&1; then
    echo "!!! Error: forego is not installed" >&2
    exit 1
  fi

  exec forego start -f "${PROCFILE:="Procfile"}"
fi
