#!/bin/bash
# Usage: handles update
# Summary: Update the project to run for its current version

set -e

cd "$(git rev-parse --show-toplevel 2>/dev/null)"
test -f "bin/update" && exec bin/update

handles-bootstrap

if [ -f "Makefile" ] && (make -q update &>/dev/null; test $? -eq 1); then
  exec make update
elif [ -f "Rakefile" ] && bundle exec rake -T update &>/dev/null; then
  exec bundle exec rake update
fi
