#!/bin/bash
# Usage: handles-setup-postgres-db <db_name>
# Summary: Set up a Postgres database

set -e
cd "$(git rev-parse --show-toplevel)"

DB_NAME="$1"

if [ -z "$DB_NAME" ]; then
  handles help setup-postgres-db >&2
  exit 1
elif ! command -v postgres &>/dev/null; then
  echo "!!! Error: postgres is not installed" >&2
  exit 1
fi

if ! dropdb --if-exists "$DB_NAME" &>/dev/null; then
  echo "!!! Error: failed to drop database" >&2
  exit 1
fi

if ! createdb "$DB_NAME" &>/dev/null; then
  echo "!!! Error: failed to create database" >&2
  exit 1
fi
