#!/bin/bash
# Usage: handles server
# Summary: Start the project locally

set -e

cd "$(git rev-parse --show-toplevel 2>/dev/null)"

handles-update

if [ -f "Procfile" ] || [ -f "Procfile.local" ]; then
  test -f "Procfile.local" && PROCFILE="Procfile.local" || PROCFILE="Procfile"
  exec forego start -f "$PROCFILE"
fi
