#!/bin/bash
# Usage: handles-setup-nginx-conf <project_name> [<source_file>]
# Summary: Generate an nginx server configuration file

set -e
cd "$(git rev-parse --show-toplevel)"

PROJECT_NAME="$1"
SOURCE_FILE="${2-"nginx.conf.erb"}"

if [ -z "$PROJECT_NAME" ] || [ -z "$SOURCE_FILE" ]; then
  handles help setup-nginx-conf >&2
  exit 1
elif [ ! -f "$SOURCE_FILE" ] || [[ "$SOURCE_FILE" != *.erb ]]; then
  echo "!!! Error: invalid source file: ${SOURCE_FILE}" >&2
  exit 1
elif ! command -v nginx &>/dev/null; then
  echo "!!! Error: nginx is not installed" >&2
  exit 1
fi

OUTPUT_FILE="${PWD}/${SOURCE_FILE//.erb}"
erb $SOURCE_FILE > $OUTPUT_FILE

if [ "$(uname -s)" = "Darwin" ]; then
  PREFIX="$(brew --prefix)"

  if [ "$(readlink /etc/resolver 2>/dev/null)" != "${PREFIX}/etc/resolver" ]; then
    sudo -p "Please enter your password to set up *.dev:" true
    sudo rm -rf /etc/resolver
    sudo ln -sf "${PREFIX}/etc/resolver" /etc/resolver
  fi

  if ! brew services list | grep "^launch_socket_server.*started" &>/dev/null; then
    sudo -p "Please enter your password to start launch_socket_server:" true
    if ! sudo brew services start launch_socket_server &>/dev/null; then
      echo "!!! Error: failed to start launch_socket_server" >&2
      exit 1
    fi
  fi

  SERVER_FILE="${PREFIX}/etc/nginx/servers/${PROJECT_NAME}.conf"
  if ! ln -sf $OUTPUT_FILE $SERVER_FILE &>/dev/null; then
    echo "!!! Error: failed to symlink ${OUTPUT_FILE} to ${SERVER_FILE}" >&2
    exit 1
  fi

  if ! brew services restart nginx &>/dev/null; then
    echo "!!! Error: failed to restart nginx" >&2
    exit 1
  fi
fi
