#!/bin/bash
# Usage: handles update
# Summary: Update the project to run for its current version

set -e

cd "$(git rev-parse --show-toplevel 2>/dev/null)"
test -f "bin/update" && exec bin/update "$@"

handles-bootstrap
