#!/bin/bash
# Usage: handles get [<user>/]<repository>
# Summary: Download a project from GitHub

set -e

PROJECT_NAME="$1"

if [[ "$PROJECT_NAME" =~ ^([A-Za-z0-9][A-Za-z0-9-]*)/([A-Za-z0-9_.][A-Za-z0-9_.-]*)$ ]]; then
  REPO_NAME="${BASH_REMATCH[2]}"
  REPO_OWNER="${BASH_REMATCH[1]}"
elif [[ "$PROJECT_NAME" =~ ^[A-Za-z0-9_.][A-Za-z0-9_.-]*$ ]]; then
  REPO_NAME="$PROJECT_NAME"
  REPO_OWNER="${GITHUB_USER:?}"
elif [ -n "$PROJECT_NAME" ]; then
  echo "!!! Error: invalid project: ${PROJECT_NAME}" >&2
  exit 1
else
  handles help get >&2
  exit 1
fi

REPO_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}"

if git ls-remote "$REPO_URL" &>/dev/null; then
  TARGET_DIR="${PROJECT_HOME:?}/${REPO_OWNER}/${REPO_NAME}"

  echo "==> Fetching ${REPO_OWNER}/${REPO_NAME}…"
  if [ ! -d "$TARGET_DIR" ]; then
    git clone --quiet "$REPO_URL" "$TARGET_DIR"
  else
    cd "$TARGET_DIR"
    git pull --quiet --rebase --autostash
  fi

  cd "$TARGET_DIR"
  handles-setup
else
  echo "!!! Error: repository ${REPO_OWNER}/${REPO_NAME} doesn't exist" >&2
  exit 1
fi
