#!/bin/bash
# Usage: handles release [major | minor | patch | <version>]
# Summary: Tag and push a release

set -e

cd "$(git rev-parse --show-toplevel 2>/dev/null)"

VERSION="$1"

if [ -z "$VERSION" ]; then
  handles help release >&2
  exit 1
elif [ -z "$(git symbolic-ref HEAD)" ]; then
  echo "!!! Error: your checkout isn't on a branch" >&2
  exit 1
elif [ "$(git symbolic-ref HEAD)" != "refs/heads/master" ]; then
  echo "!!! Error: your checkout isn't on master" >&2
  exit 1
elif [ ! -z "$(git status --porcelain 2>/dev/null)" ]; then
  echo "!!! Error: there are uncommitted changes" >&2
  exit 1
elif ! git fetch --quiet --tags origin; then
  echo "!!! Error: running 'git fetch' failed" >&2
  exit 1
elif [ "$(git rev-list --count HEAD..origin/master)" != "0" ]; then
  echo "!!! Error: there have been upstream changes on master" >&2
  exit 1
fi

CURRENT_VERSION="$(git describe --tags --abbrev=0 --match='v[0-9]*' 2>/dev/null || true)"
VERSION_REGEX="^v(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))?)?$"

if [[ "$CURRENT_VERSION" =~ $VERSION_REGEX ]]; then
  MAJOR="${BASH_REMATCH[1]}"
  MINOR="${BASH_REMATCH[3]}"
  PATCH="${BASH_REMATCH[5]}"
elif [ -z "$CURRENT_VERSION" ]; then
  MAJOR="0"
  MINOR="0"
  PATCH="0"
fi

case $VERSION in
  major|+M) VERSION="v$((${MAJOR:-0} + 1))${MINOR:+.0}${PATCH:+.0}" ;;
  minor|+m) VERSION="v${MAJOR:-0}.$((${MINOR:-0} + 1))${PATCH:+.0}" ;;
  patch|+p) VERSION="v${MAJOR:-0}.${MINOR:-0}.$((${PATCH:-0} + 1))" ;;
esac

if [[ ! "$VERSION" =~ $VERSION_REGEX ]]; then
  echo "!!! Error: invalid version: ${VERSION}" >&2
  exit 1
elif git describe --exact-match "$VERSION" &>/dev/null; then
  echo "!!! Error: ${VERSION} tag already exists" >&2
  exit 1
elif [ -n "$CURRENT_VERSION" ] && [ "$(git rev-list --count "$CURRENT_VERSION"..HEAD)" == "0" ]; then
  echo "!!! Error: there are no commits to release" >&2
  exit 1
fi

if [ -f "package.json" ]; then
  echo "==> Bumping version…"

  if ! npm version --no-git-tag-version "${VERSION#v}" &>/dev/null; then
    echo "!!! Error: failed to bump version" >&2
    exit 1
  fi

  test -f "npm-shrinkwrap.json" && git add --update npm-shrinkwrap.json
  test -f "package-lock.json" && git add --update package-lock.json
  git add --update package.json
fi

if ! git diff-index --cached --quiet HEAD --; then
  echo "==> Preparing release…"
  if ! git commit -m ":bookmark: Release ${VERSION}" &>/dev/null; then
    echo "!!! Error: failed to prepare release" >&2
    exit 1
  fi
fi

echo "==> Tagging release…"
if ! git tag -s "$VERSION" -m ":bookmark: Tag ${VERSION}" &>/dev/null; then
  echo "!!! Error: failed to tag release" >&2
  exit 1
fi

echo "==> Pushing master to origin…"
if ! git push origin master &>/dev/null; then
  echo "!!! Error: failed to push to master" >&2
  exit 1
fi

echo "==> Pushing tag to origin…"
if ! git push origin "$VERSION" &>/dev/null; then
  echo "!!! Error: failed to push tag to origin" >&2
  exit 1
fi

echo "==> Successfully released ${VERSION}!"
