#!/bin/bash
# Usage: handles-sync [<target_dir>]
# Summary: Fetch from upstream and update local branches for downloaded projects

set -e

TARGET_DIR="${1-${PROJECT_HOME}}"

shopt -s nullglob
for path in "$TARGET_DIR"/**/*/.git; do
  path="${path%/*}"
  cd "$path"

  echo "==> Syncing ${path#${PROJECT_HOME}/}…"
  hub sync 2>/dev/null || true
  git branch -vv | grep '.*/.*: gone]' | awk '{print $1}' | xargs git branch -D || true
done
shopt -u nullglob
