#!/bin/bash
# Usage: handles server
# Summary: Start the project locally

set -e
cd "$(git rev-parse --show-toplevel)"

handles-update

test -f "Procfile.local" && PROCFILE="Procfile.local"

if [ "$(uname -s)" = "Darwin" ]; then
  if ! command -v forego &>/dev/null; then
    echo "!!! Error: forego is not installed" >&2
    exit 1
  fi

  exec forego start -f "${PROCFILE:="Procfile"}"
fi
