#!/bin/bash
# Usage: handles-setup
# Summary: Set up the project to run for the first time

set -e
cd "$(git rev-parse --show-toplevel)"

handles-bootstrap

if [ "$(uname -s)" = "Darwin" ]; then
  PREFIX="$(brew --prefix)"
fi

export LOG_DIR="${PREFIX}/var/log"
export PROJECT="$(echo $PWD | sed -e "s:^${PROJECTS_HOME}\\(/${GITHUB_USER}\\)\{0,1\}/\{0,1\}::g;s:\/:-:g")"
export PROJECT_ROOT="$PWD"
export SOCKET_DIR="${PREFIX}/var/run"

if [ -f ".env.example" ]; then
  echo "==> Generating environment file…"
  handles-setup-dotenv
fi

if [ -f "nginx.conf.erb" ] && [ "$(uname -s)" = "Darwin" ]; then
  export NGINX_LOG_DIR="${LOG_DIR}/nginx"

  echo "==> Creating nginx server configuration file…"
  erb nginx.conf.erb > nginx.conf

  echo "==> Enabling nginx server configuration file…"
  ln -sf "${PROJECT_ROOT}/nginx.conf" "${PREFIX}/etc/nginx/servers/${PROJECT}.conf"

  echo "==> Reloading nginx…"
  if ! brew services reload nginx &>/dev/null; then
    echo "!!! Error: failed to reload nginx!" >&2
    exit 1
  fi

  if [ "$(readlink /etc/resolver 2>/dev/null)" != "${PREFIX}/etc/resolver" ]; then
    echo "==> Resolving *.dev to 127.0.0.1…"
    sudo -p "Please enter your password (for sudo access):" true
    sudo rm -rf /etc/resolver
    sudo ln -sf "${PREFIX}/etc/resolver" /etc/resolver
  fi

  if ! brew services list | grep "^launch_socket_server.*started" &>/dev/null; then
    echo "==> Starting launch_socket_server…"
    sudo -p "Please enter your password (for sudo access):" true
    if ! sudo brew services start launch_socket_server &>/dev/null; then
      echo "!!! Error: failed to restart launch_socket_server!" >&2
      exit 1
    fi
  fi
fi

echo "==> Your project is now ready to go!"
