#!/bin/bash
# Usage: handles-setup
# Summary: Set up the project to run for the first time

set -e
cd "$(git rev-parse --show-toplevel)"

handles-bootstrap

if [ -f ".env.example" ]; then
  echo "==> Creating .env file…"
  cp .env.example .env
fi

echo "==> Your project is now ready to go!"
