#!/bin/bash
# Usage: handles-setup-dotenv [<input_file>]
# Summary: Generate an environment file

set -e
cd "$(git rev-parse --show-toplevel)"

INPUT_FILE="${1-".env.example"}"

if [ -z "$INPUT_FILE" ]; then
  handles help setup-dotenv >&2
  exit 1
elif [ ! -f "$INPUT_FILE" ]; then
  echo "!!! Error: invalid input file: ${INPUT_FILE}" >&2
  exit 1
fi

cp $INPUT_FILE .env

sed -i -e "s/^SECRET_KEY=$/SECRET_KEY=$(echo $(openssl rand -base64 48) | sed -e 's/[\/&]/\\&/g')/" .env
for var in $(env | sed -ne "s/\([^=]*\)=.*/\1/p" | uniq); do
  sed -i -e "s/^$var=$/$var=$(eval echo "\$$var" | sed -e 's/[\/&]/\\&/g')/" .env
done
